library(haven)
library(dplyr)
A=read_sav("A.sav")
A
str(A)
View(A)
D=read_sav("discrim.sav")
D
system("ls -l ~/Downloads/*.s*")
pers=read_sav("~/Downloads/personality.sav")
pers
head(pers)
library(foreign)
pers=read.spss("~/Downloads/personality.sav")
pers
write.table(pers,"personality.txt")
attributes(pers)$variable.labels
saq=read_sav("~/Downloads/SAQ.sav")
saq
saq=read.spss("~/Downloads/SAQ.sav")
attributes(saq)$variable.labels
stooges=read_sas("~/Downloads/three_stooges.sas7bdat")
stooges

install.packages("psych")
library(psych)
data(epi)
data(epi.dictionary)
epi.dictionary
data(epi.bfi)
epi.bfi
epi.1=princomp(epi.bfi,cor=T)
plot(epi.1,type="l")
epi.2=factanal(epi.bfi,3,scores="r")
epi.2
epi.3=factanal(epi.bfi,4,scores="r")
epi.3
