# packages and conflict preferences for my notes
library(conflicted)
library(tidyverse)
library(ggbiplot)
library(lavaan)
library(spatstat)
library(MASS)
library(ggrepel)
library(car)
library(broom)
library(ggmap)
conflict_prefer("arrange", "dplyr")
conflict_prefer("mutate", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("summarize", "dplyr")
conflict_prefer("count", "dplyr")
conflict_prefer("select", "dplyr")
