/*  File generated by StatWeave  */
data _null_; file print;
put "--- Output file from StatWeave, engine = SASEngine ---";
options nocenter nodate nonumber skip=0 ls=100 formdlim=' '
  formchar = '|----|+|---+=|-/\<>*';
title; footnote;



/* ---- Chunk 1: "remote-sensing-1-SAS" ----- */
data _null_; file print;
put "!-StatWeave-!/swv~line 49~UDNVO4/out";
filename grafout "remote-sensing-1-SAS-fig.eps";
goptions reset=goptions;
goptions device=PSEPSF gsfname=grafout gsfmode=replace;
goptions noborder horigin=.2in vorigin=.2in;
goptions xmax = 6.0in ymax = 6.0in;
goptions hsize = 5.8in vsize = 5.8in;
goptions vpos = 36;
data crops;
    infile "remote-sensing.dat";
    input Crop $ x1-x4 label $;
    
proc discrim can list pool=test out=zz crosslist;
    class Crop;
    var x1-x4;

goptions reset=all;
symbol1 c=blue v=triangle;
symbol2 c=cyan v=circle;
symbol3 c=red v=diamond;
symbol4 c=black v=plus;
symbol5 c=green v=x;

proc gplot;
plot Can1 * Can2 = Crop;
run;
data _null_; file print;
put "@-StatWeave-!/swv~line 49~UDNVO4/out";
run; quit;

