/*  File generated by StatWeave  */
data _null_; file print;
put "--- Output file from StatWeave, engine = SASEngine ---";
options nocenter nodate nonumber skip=0 ls=100 formdlim=' '
  formchar = '|----|+|---+=|-/\<>*';
title; footnote;



/* ---- Chunk 1: "sero-1-SAS" ----- */
data _null_; file print;
put "!-StatWeave-!/swv~line 21~HDXUC4/out";
data sero;
  infile "sero.dat";
  input group age n r;
  obspos=r/n;

proc print;

proc logistic;
  model r/n = age / lackfit;
  output out=sero2 pred=pred;

proc print data=sero2;

run;
data _null_; file print;
put "@-StatWeave-!/swv~line 21~HDXUC4/out";

